const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

const detectDockerEnvironment = () => {
	// Check if running inside Docker
	if (fs.existsSync('/.dockerenv')) {
		return true;
	}
	
	// Check cgroup
	try {
		const cgroup = fs.readFileSync('/proc/self/cgroup', 'utf8');
		return cgroup.includes('docker');
	} catch {
		return false;
	}
};

const generateDockerfile = (options = {}) => {
	const port = options.port || 8080;
	const buildDir = options.buildDir || 'dist';
	
	let dockerfile = `# Generated by GIB-RUNS
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy application files
COPY . .

`;

	if (options.buildCommand) {
		dockerfile += `# Build application
RUN ${options.buildCommand}

`;
	}

	dockerfile += `# Expose port
EXPOSE ${port}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD node -e "require('http').get('http://localhost:${port}/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"

# Start server
CMD ["npx", "gib-runs", "${buildDir}", "--port=${port}", "--host=0.0.0.0"]
`;

	return dockerfile;
};

const generateDockerCompose = (options = {}) => {
	const serviceName = options.serviceName || 'app';
	const port = options.port || 8080;
	const buildDir = options.buildDir || 'dist';
	
	const compose = {
		version: '3.8',
		services: {}
	};
	
	compose.services[serviceName] = {
		build: '.',
		ports: [`${port}:${port}`],
		environment: {
			NODE_ENV: 'production',
			PORT: port
		},
		volumes: [
			`./${buildDir}:/app/${buildDir}`,
			'./node_modules:/app/node_modules'
		],
		restart: 'unless-stopped',
		healthcheck: {
			test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', `http://localhost:${port}/health`],
			interval: '30s',
			timeout: '3s',
			retries: 3,
			start_period: '5s'
		}
	};
	
	return compose;
};

const generateDockerIgnore = () => {
	return `# GIB-RUNS Docker Ignore
node_modules
npm-debug.log
.git
.gitignore
.env
.env.local
.DS_Store
*.log
coverage
.vscode
.idea
dist
build
.next
.nuxt
`;
};

const saveDockerFiles = (cwd, options = {}) => {
	const dockerfilePath = path.join(cwd, 'Dockerfile');
	const composePath = path.join(cwd, 'docker-compose.yml');
	const ignorePath = path.join(cwd, '.dockerignore');
	
	try {
		// Generate Dockerfile
		if (!fs.existsSync(dockerfilePath) || options.force) {
			const dockerfile = generateDockerfile(options);
			fs.writeFileSync(dockerfilePath, dockerfile, 'utf8');
			console.log(chalk.green('  ✓ Created Dockerfile'));
		} else {
			console.log(chalk.yellow('  ⚠ Dockerfile already exists (use --force to overwrite)'));
		}
		
		// Generate docker-compose.yml
		if (!fs.existsSync(composePath) || options.force) {
			const compose = generateDockerCompose(options);
			const yaml = require('js-yaml');
			fs.writeFileSync(composePath, yaml.dump(compose), 'utf8');
			console.log(chalk.green('  ✓ Created docker-compose.yml'));
		} else {
			console.log(chalk.yellow('  ⚠ docker-compose.yml already exists (use --force to overwrite)'));
		}
		
		// Generate .dockerignore
		if (!fs.existsSync(ignorePath) || options.force) {
			const ignore = generateDockerIgnore();
			fs.writeFileSync(ignorePath, ignore, 'utf8');
			console.log(chalk.green('  ✓ Created .dockerignore'));
		}
		
		console.log(chalk.cyan('\n  📦 Docker files generated successfully!'));
		console.log(chalk.gray('  Build: ') + chalk.white('docker-compose build'));
		console.log(chalk.gray('  Run:   ') + chalk.white('docker-compose up'));
		console.log(chalk.gray('  Stop:  ') + chalk.white('docker-compose down\n'));
		
		return true;
	} catch (e) {
		console.error(chalk.red('  ✖ Failed to generate Docker files: ') + e.message);
		return false;
	}
};

const getDockerRecommendations = () => {
	return {
		host: '0.0.0.0',
		compression: true,
		logLevel: 2,
		enableHealth: true,
		cors: true
	};
};

module.exports = {
	detectDockerEnvironment,
	generateDockerfile,
	generateDockerCompose,
	generateDockerIgnore,
	saveDockerFiles,
	getDockerRecommendations
};
